"""add percentage to ai_readiness

Revision ID: 18816ceb9477
Revises: 8da9f308ba2c
Create Date: 2025-12-24 11:43:16.256702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18816ceb9477'
down_revision = '8da9f308ba2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_readiness', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Integer(), nullable=False))
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('answers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_readiness', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###
