"""Add contact_messages table

Revision ID: 91d91e66b9f7
Revises: 7a17140dd0bc
Create Date: 2025-12-14 21:06:05.096646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d91e66b9f7'
down_revision = '7a17140dd0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('score_clients')
    op.drop_table('score_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('question_number', sa.INTEGER(), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=500), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['score_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
